FROM apache/airflow:2.9.3-python3.11
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1
ENV PIP_INSTALL_OPTIONS "--no-cache-dir --progress-bar off --quiet --no-color --no-input"

USER root
RUN apt update && \
    apt install -y p7zip-full && \
    apt clean

USER airflow
RUN pip install ${PIP_INSTALL_OPTIONS} --upgrade pip; \
    pip install ${PIP_INSTALL_OPTIONS} \
        --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.3/constraints-3.11.txt" \
        "apache-airflow[postgres,celery,redis,yandex,telegram,http,ftp,sftp,mssql,mysql,odbc,oracle]==2.9.3" && \
    pip install ${PIP_INSTALL_OPTIONS} \
        acryl-datahub==0.14.1.12 \
        atlassian-python-api==3.41.14 \
        dag-factory==0.22.0 \
        dbt-postgres \
        fastparquet==2024.11.0 \
        jira==3.4.0 \
        mytracker-export-api \
        oauth2client \
        openpyxl \
        requests_ntlm==1.3.0 \
        stream-unzip==0.0.70 \
        xlrd && \
    pip install ${PIP_INSTALL_OPTIONS} mailru-im-bot==0.0.21 && \
    pip install ${PIP_INSTALL_OPTIONS} --upgrade requests
