FROM apache/airflow:2.9.2
# COPY requirements.txt /requirements.txt
ADD requirements.txt .
# RUN pip install --user --upgrade pip
# RUN pip install --no-cache-dir --user -r /requirements.txt
RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt