FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    sudo \
    git \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dbt_files /opt/app/dbt

CMD ["dbt", "run"]